version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: biblia
      MONGO_INITDB_ROOT_PASSWORD: 114855
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
